import { NextResponse } from 'next/server';

const MP_API_URL = 'https://api.mercadopago.com/v1/orders';

export async function POST(request: Request) {
    try {
        const { amount, orderId, deviceId } = await request.json();
        const accessToken = process.env.MERCADOPAGO_ACCESS_TOKEN;

        if (!accessToken) {
            return NextResponse.json({ error: 'Mercado Pago Access Token not configured' }, { status: 500 });
        }

        if (!deviceId) {
            return NextResponse.json({ error: 'Device ID is required' }, { status: 400 });
        }

        const externalRef = `order_${orderId.slice(0, 10)}_${Date.now()}`;

        const response = await fetch(MP_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json',
                'X-Idempotency-Key': externalRef,
            },
            body: JSON.stringify({
                type: 'point',
                external_reference: externalRef,
                expiration_time: 'PT15M',
                transactions: {
                    payments: [
                        {
                            amount: Number(parseFloat(amount).toFixed(2))
                        }
                    ]
                },
                config: {
                    point: {
                        terminal_id: deviceId,
                        print_on_terminal: 'no_ticket'
                    }
                },
                description: `POS Order #${orderId.slice(0, 4)}`
            }),
        });

        const data = await response.json();

        if (!response.ok) {
            console.error('MP Order Error:', data);
            return NextResponse.json({ error: data.message || 'Failed to create payment order' }, { status: response.status });
        }

        // Return the Order ID generated by MP
        return NextResponse.json({ id: data.id });
    } catch (error) {
        console.error('Internal Server Error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}

export async function GET(request: Request) {
    try {
        const { searchParams } = new URL(request.url);
        const orderId = searchParams.get('paymentIntentId'); // We reuse this field name for simplicity in frontend
        const accessToken = process.env.MERCADOPAGO_ACCESS_TOKEN;

        if (!accessToken) {
            return NextResponse.json({ error: 'Mercado Pago Access Token not configured' }, { status: 500 });
        }

        if (!orderId) {
            return NextResponse.json({ error: 'Missing orderId parameter' }, { status: 400 });
        }

        const response = await fetch(`${MP_API_URL}/${orderId}`, {
            headers: {
                'Authorization': `Bearer ${accessToken}`,
            },
        });

        const data = await response.json();

        if (!response.ok) {
            return NextResponse.json({ error: 'Failed to fetch status' }, { status: response.status });
        }

        /**
         * Mapping Orders API status to the frontend's expected format
         * Expected statuses: FINISHED, CLOSED, CANCELED, EXPIRED
         */
        let status = data.status;
        if (status === 'processed' || status === 'accredited') {
            status = 'FINISHED';
        } else if (status === 'canceled' || status === 'failed') {
            status = 'CANCELED';
        } else if (status === 'expired') {
            status = 'EXPIRED';
        }

        return NextResponse.json({ status });
    } catch (error) {
        console.error('Internal Server Error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
